---


- hosts: nginx
  become: true
  tasks:
    
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
   
    - name: install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
        
    - name: nginx enable
      systemd:
        name: nginx.service
        enabled: yes
         
    - name: "Delete /var/www/html folder"
      ansible.builtin.file:
        path: "/var/www/html/"
        state: "absent"
    
    - name: "Copy html"
      ansible.builtin.copy:
        src: "./index.html"
        dest: "/var/www/html/"
        owner: "root"
        group: "root"
        mode: "0644"
      notify: Restart nginx
      
    
    - name: Download filebeat
      ansible.builtin.command: wget https://mirror.yandex.ru/mirrors/elastic/8/pool/main/f/filebeat/filebeat-8.9.2-amd64.deb
      when: "'filebeat' not in ansible_facts.packages"
      
    - name: Install filebeat
      ansible.builtin.command: dpkg -i filebeat-8.9.2-amd64.deb
      when: 
        - ansible_os_family == "Debian"
        - "'filebeat' not in ansible_facts.packages"
        
    - name: Filebeat enable
      systemd:
        name: filebeat.service
        enabled: yes

   - name: "Copy filebeat_config"
      ansible.builtin.copy:
        src: "./filebeat.yml"
        dest: "/etc/filebeat/"
        owner: "root"
        group: "root"
        mode: "0644"
      notify: Restart filebeat
        
      
  handlers:     
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
        
    - name: Restart filebeat
      service:
        name: filebeat
        state: restarted    
        
...
